require:
- rubocop-rspec
- rubocop-factory_bot
- rubocop-graphql
- rubocop-rails

AllCops:
  Exclude:
    - 'bin/bundle'
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'db/**/*'